FROM local/astrbot:4.26.7-isolated

ENTRYPOINT []
WORKDIR /work

COPY requirements.txt /tmp/astrbotex-plugin-requirements.txt
RUN python -m pip install --no-cache-dir -r /tmp/astrbotex-plugin-requirements.txt

COPY . /work/astrbot_plugin_astrbotex_interaction

CMD ["python", "-m", "unittest", "discover", "-s", "/work/astrbot_plugin_astrbotex_interaction/tests", "-v"]
